export const COUNTRIES = [
    { "name": "Canada", "code": "CA" },
    { "name": "United Kingdom", "code": "GB" },
    { "name": "United States", "code": "US" },
]
export const PROVINCES = [
	{ "name": "Alberta","code":"AB"},
	{ "name": "British Columbia","code":"BC"},
	{ "name": "Manitoba","code":"MB"},
	{ "name": "New Brunswick","code":"NB"},
	{ "name": "Newfoundland and Labrador","code":"NL"},
	{ "name": "Nova Scotia","code":"NS"},
	{ "name": "Northwest Territories","code":"NT"},
	{ "name": "Nunavut","code":"NU"},
	{ "name": "Ontario","code":"ON"},
	{ "name": "Prince Edward Island","code":"PE"},
	{ "name": "Quebec","code":"QC"},
	{ "name": "Saskatchewan","code":"SK"},
	{ "name": "Yukon","code":"YT"},
	]


/*export const COUNTRIES = [
    { "name": "Afghanistan", "code": "AF" },
    { "name": "Aland Islands", "code": "AX" },
    { "name": "Albania", "code": "AL" },
    { "name": "Algeria", "code": "DZ" },
    { "name": "American Samoa", "code": "AS" },
    { "name": "AndorrA", "code": "AD" },
    { "name": "Angola", "code": "AO" },
    { "name": "Anguilla", "code": "AI" },
    { "name": "Antarctica", "code": "AQ" },
    { "name": "Antigua and Barbuda", "code": "AG" },
    { "name": "Argentina", "code": "AR" },
    { "name": "Armenia", "code": "AM" },
    { "name": "Aruba", "code": "AW" },
    { "name": "Australia", "code": "AU" },
    { "name": "Austria", "code": "AT" },
    { "name": "Azerbaijan", "code": "AZ" },
    { "name": "Bahamas", "code": "BS" },
    { "name": "Bahrain", "code": "BH" },
    { "name": "Bangladesh", "code": "BD" },
    { "name": "Barbados", "code": "BB" },
    { "name": "Belarus", "code": "BY" },
    { "name": "Belgium", "code": "BE" },
    { "name": "Belize", "code": "BZ" },
    { "name": "Benin", "code": "BJ" },
    { "name": "Bermuda", "code": "BM" },
    { "name": "Bhutan", "code": "BT" },
    { "name": "Bolivia", "code": "BO" },
    { "name": "Bosnia and Herzegovina", "code": "BA" },
    { "name": "Botswana", "code": "BW" },
    { "name": "Bouvet Island", "code": "BV" },
    { "name": "Brazil", "code": "BR" },
    { "name": "British Indian Ocean Territory", "code": "IO" },
    { "name": "Brunei Darussalam", "code": "BN" },
    { "name": "Bulgaria", "code": "BG" },
    { "name": "Burkina Faso", "code": "BF" },
    { "name": "Burundi", "code": "BI" },
    { "name": "Cambodia", "code": "KH" },
    { "name": "Cameroon", "code": "CM" },
    { "name": "Canada", "code": "CA" },
    { "name": "Cape Verde", "code": "CV" },
    { "name": "Cayman Islands", "code": "KY" },
    { "name": "Central African Republic", "code": "CF" },
    { "name": "Chad", "code": "TD" },
    { "name": "Chile", "code": "CL" },
    { "name": "China", "code": "CN" },
    { "name": "Christmas Island", "code": "CX" },
    { "name": "Cocos (Keeling) Islands", "code": "CC" },
    { "name": "Colombia", "code": "CO" },
    { "name": "Comoros", "code": "KM" },
    { "name": "Congo", "code": "CG" },
    { "name": "Congo, The Democratic Republic of the", "code": "CD" },
    { "name": "Cook Islands", "code": "CK" },
    { "name": "Costa Rica", "code": "CR" },
    {
        "name": "Cote D\"Ivoire", "code": "CI"
    },
    { "name": "Croatia", "code": "HR" },
    { "name": "Cuba", "code": "CU" },
    { "name": "Cyprus", "code": "CY" },
    { "name": "Czech Republic", "code": "CZ" },
    { "name": "Denmark", "code": "DK" },
    { "name": "Djibouti", "code": "DJ" },
    { "name": "Dominica", "code": "DM" },
    { "name": "Dominican Republic", "code": "DO" },
    { "name": "Ecuador", "code": "EC" },
    { "name": "Egypt", "code": "EG" },
    { "name": "El Salvador", "code": "SV" },
    { "name": "Equatorial Guinea", "code": "GQ" },
    { "name": "Eritrea", "code": "ER" },
    { "name": "Estonia", "code": "EE" },
    { "name": "Ethiopia", "code": "ET" },
    { "name": "Falkland Islands (Malvinas)", "code": "FK" },
    { "name": "Faroe Islands", "code": "FO" },
    { "name": "Fiji", "code": "FJ" },
    { "name": "Finland", "code": "FI" },
    { "name": "France", "code": "FR" },
    { "name": "French Guiana", "code": "GF" },
    { "name": "French Polynesia", "code": "PF" },
    { "name": "French Southern Territories", "code": "TF" },
    { "name": "Gabon", "code": "GA" },
    { "name": "Gambia", "code": "GM" },
    { "name": "Georgia", "code": "GE" },
    { "name": "Germany", "code": "DE" },
    { "name": "Ghana", "code": "GH" },
    { "name": "Gibraltar", "code": "GI" },
    { "name": "Greece", "code": "GR" },
    { "name": "Greenland", "code": "GL" },
    { "name": "Grenada", "code": "GD" },
    { "name": "Guadeloupe", "code": "GP" },
    { "name": "Guam", "code": "GU" },
    { "name": "Guatemala", "code": "GT" },
    { "name": "Guernsey", "code": "GG" },
    { "name": "Guinea", "code": "GN" },
    { "name": "Guinea-Bissau", "code": "GW" },
    { "name": "Guyana", "code": "GY" },
    { "name": "Haiti", "code": "HT" },
    { "name": "Heard Island and Mcdonald Islands", "code": "HM" },
    { "name": "Holy See (Vatican City State)", "code": "VA" },
    { "name": "Honduras", "code": "HN" },
    { "name": "Hong Kong", "code": "HK" },
    { "name": "Hungary", "code": "HU" },
    { "name": "Iceland", "code": "IS" },
    { "name": "India", "code": "IN" },
    { "name": "Indonesia", "code": "ID" },
    { "name": "Iran, Islamic Republic Of", "code": "IR" },
    { "name": "Iraq", "code": "IQ" },
    { "name": "Ireland", "code": "IE" },
    { "name": "Isle of Man", "code": "IM" },
    { "name": "Israel", "code": "IL" },
    { "name": "Italy", "code": "IT" },
    { "name": "Jamaica", "code": "JM" },
    { "name": "Japan", "code": "JP" },
    { "name": "Jersey", "code": "JE" },
    { "name": "Jordan", "code": "JO" },
    { "name": "Kazakhstan", "code": "KZ" },
    { "name": "Kenya", "code": "KE" },
    { "name": "Kiribati", "code": "KI" },
    {
        "name": "Korea, Democratic People\"S Republic of", "code": "KP"
    },
    { "name": "Korea, Republic of", "code": "KR" },
    { "name": "Kuwait", "code": "KW" },
    { "name": "Kyrgyzstan", "code": "KG" },
    {
        "name": "Lao People\"S Democratic Republic", "code": "LA"
    },
    { "name": "Latvia", "code": "LV" },
    { "name": "Lebanon", "code": "LB" },
    { "name": "Lesotho", "code": "LS" },
    { "name": "Liberia", "code": "LR" },
    { "name": "Libyan Arab Jamahiriya", "code": "LY" },
    { "name": "Liechtenstein", "code": "LI" },
    { "name": "Lithuania", "code": "LT" },
    { "name": "Luxembourg", "code": "LU" },
    { "name": "Macao", "code": "MO" },
    { "name": "Macedonia, The Former Yugoslav Republic of", "code": "MK" },
    { "name": "Madagascar", "code": "MG" },
    { "name": "Malawi", "code": "MW" },
    { "name": "Malaysia", "code": "MY" },
    { "name": "Maldives", "code": "MV" },
    { "name": "Mali", "code": "ML" },
    { "name": "Malta", "code": "MT" },
    { "name": "Marshall Islands", "code": "MH" },
    { "name": "Martinique", "code": "MQ" },
    { "name": "Mauritania", "code": "MR" },
    { "name": "Mauritius", "code": "MU" },
    { "name": "Mayotte", "code": "YT" },
    { "name": "Mexico", "code": "MX" },
    { "name": "Micronesia, Federated States of", "code": "FM" },
    { "name": "Moldova, Republic of", "code": "MD" },
    { "name": "Monaco", "code": "MC" },
    { "name": "Mongolia", "code": "MN" },
    { "name": "Montenegro", "code": "ME" },
    { "name": "Montserrat", "code": "MS" },
    { "name": "Morocco", "code": "MA" },
    { "name": "Mozambique", "code": "MZ" },
    { "name": "Myanmar", "code": "MM" },
    { "name": "Namibia", "code": "NA" },
    { "name": "Nauru", "code": "NR" },
    { "name": "Nepal", "code": "NP" },
    { "name": "Netherlands", "code": "NL" },
    { "name": "Netherlands Antilles", "code": "AN" },
    { "name": "New Caledonia", "code": "NC" },
    { "name": "New Zealand", "code": "NZ" },
    { "name": "Nicaragua", "code": "NI" },
    { "name": "Niger", "code": "NE" },
    { "name": "Nigeria", "code": "NG" },
    { "name": "Niue", "code": "NU" },
    { "name": "Norfolk Island", "code": "NF" },
    { "name": "Northern Mariana Islands", "code": "MP" },
    { "name": "Norway", "code": "NO" },
    { "name": "Oman", "code": "OM" },
    { "name": "Pakistan", "code": "PK" },
    { "name": "Palau", "code": "PW" },
    { "name": "Palestinian Territory, Occupied", "code": "PS" },
    { "name": "Panama", "code": "PA" },
    { "name": "Papua New Guinea", "code": "PG" },
    { "name": "Paraguay", "code": "PY" },
    { "name": "Peru", "code": "PE" },
    { "name": "Philippines", "code": "PH" },
    { "name": "Pitcairn", "code": "PN" },
    { "name": "Poland", "code": "PL" },
    { "name": "Portugal", "code": "PT" },
    { "name": "Puerto Rico", "code": "PR" },
    { "name": "Qatar", "code": "QA" },
    { "name": "Reunion", "code": "RE" },
    { "name": "Romania", "code": "RO" },
    { "name": "Russian Federation", "code": "RU" },
    { "name": "RWANDA", "code": "RW" },
    { "name": "Saint Helena", "code": "SH" },
    { "name": "Saint Kitts and Nevis", "code": "KN" },
    { "name": "Saint Lucia", "code": "LC" },
    { "name": "Saint Pierre and Miquelon", "code": "PM" },
    { "name": "Saint Vincent and the Grenadines", "code": "VC" },
    { "name": "Samoa", "code": "WS" },
    { "name": "San Marino", "code": "SM" },
    { "name": "Sao Tome and Principe", "code": "ST" },
    { "name": "Saudi Arabia", "code": "SA" },
    { "name": "Senegal", "code": "SN" },
    { "name": "Serbia", "code": "RS" },
    { "name": "Seychelles", "code": "SC" },
    { "name": "Sierra Leone", "code": "SL" },
    { "name": "Singapore", "code": "SG" },
    { "name": "Slovakia", "code": "SK" },
    { "name": "Slovenia", "code": "SI" },
    { "name": "Solomon Islands", "code": "SB" },
    { "name": "Somalia", "code": "SO" },
    { "name": "South Africa", "code": "ZA" },
    { "name": "South Georgia and the South Sandwich Islands", "code": "GS" },
    { "name": "Spain", "code": "ES" },
    { "name": "Sri Lanka", "code": "LK" },
    { "name": "Sudan", "code": "SD" },
    { "name": "Suriname", "code": "SR" },
    { "name": "Svalbard and Jan Mayen", "code": "SJ" },
    { "name": "Swaziland", "code": "SZ" },
    { "name": "Sweden", "code": "SE" },
    { "name": "Switzerland", "code": "CH" },
    { "name": "Syrian Arab Republic", "code": "SY" },
    { "name": "Taiwan, Province of China", "code": "TW" },
    { "name": "Tajikistan", "code": "TJ" },
    { "name": "Tanzania, United Republic of", "code": "TZ" },
    { "name": "Thailand", "code": "TH" },
    { "name": "Timor-Leste", "code": "TL" },
    { "name": "Togo", "code": "TG" },
    { "name": "Tokelau", "code": "TK" },
    { "name": "Tonga", "code": "TO" },
    { "name": "Trinidad and Tobago", "code": "TT" },
    { "name": "Tunisia", "code": "TN" },
    { "name": "Turkey", "code": "TR" },
    { "name": "Turkmenistan", "code": "TM" },
    { "name": "Turks and Caicos Islands", "code": "TC" },
    { "name": "Tuvalu", "code": "TV" },
    { "name": "Uganda", "code": "UG" },
    { "name": "Ukraine", "code": "UA" },
    { "name": "United Arab Emirates", "code": "AE" },
    { "name": "United Kingdom", "code": "GB" },
    { "name": "United States", "code": "US" },
    { "name": "United States Minor Outlying Islands", "code": "UM" },
    { "name": "Uruguay", "code": "UY" },
    { "name": "Uzbekistan", "code": "UZ" },
    { "name": "Vanuatu", "code": "VU" },
    { "name": "Venezuela", "code": "VE" },
    { "name": "Viet Nam", "code": "VN" },
    { "name": "Virgin Islands, British", "code": "VG" },
    { "name": "Virgin Islands, U.S.", "code": "VI" },
    { "name": "Wallis and Futuna", "code": "WF" },
    { "name": "Western Sahara", "code": "EH" },
    { "name": "Yemen", "code": "YE" },
    { "name": "Zambia", "code": "ZM" },
    { "name": "Zimbabwe", "code": "ZW" }
]*/

export const GENDERS = [
    { "name": "Male", "code": "m" },
    { "name": "Female", "code": "f" }
]

export const LANGUAGESPOKEN = [{"name":"Abkhazian","code":"ab"},
{"name":"Afar","code":"aa"},
{"name":"Afrikaans","code":"af"},
{"name":"Akan","code":"ak"},
{"name":"Albanian","code":"sq"},
{"name":"Amharic","code":"am"},
{"name":"Arabic","code":"ar"},
{"name":"Aragonese","code":"an"},
{"name":"Armenian","code":"hy"},
{"name":"Assamese","code":"as"},
{"name":"Avaric","code":"av"},
{"name":"Avestan","code":"ae"},
{"name":"Aymara","code":"ay"},
{"name":"Azerbaijani","code":"az"},
{"name":"Bambara","code":"bm"},
{"name":"Bashkir","code":"ba"},
{"name":"Basque","code":"eu"},
{"name":"Belarusian","code":"be"},
{"name":"Bengali(Bangla)","code":"bn"},
{"name":"Bihari","code":"bh"},
{"name":"Bislama","code":"bi"},
{"name":"Bosnian","code":"bs"},
{"name":"Breton","code":"br"},
{"name":"Bulgarian","code":"bg"},
{"name":"Burmese","code":"my"},
{"name":"Catalan","code":"ca"},
{"name":"Chamorro","code":"ch"},
{"name":"Chechen","code":"ce"},
{"name":"ChichewaChewaNyanja","code":"ny"},
{"name":"Chinese","code":"zh"},
{"name":"Chinese(Simplified)","code":"zh-Hans"},
{"name":"Chinese(Traditional)","code":"zh-Hant"},
{"name":"Chuvash","code":"cv"},
{"name":"Cornish","code":"kw"},
{"name":"Corsican","code":"co"},
{"name":"Cree","code":"cr"},
{"name":"Croatian","code":"hr"},
{"name":"Czech","code":"cs"},
{"name":"Danish","code":"da"},
{"name":"Divehi","code":"dv"},
{"name":"Dutch","code":"nl"},
{"name":"Dzongkha","code":"dz"},
{"name":"English","code":"en"},
{"name":"Esperanto","code":"eo"},
{"name":"Estonian","code":"et"},
{"name":"Ewe","code":"ee"},
{"name":"Faroese","code":"fo"},
{"name":"Fijian","code":"fj"},
{"name":"Finnish","code":"fi"},
{"name":"French","code":"fr"},
{"name":"FulaFulahPulaarPular","code":"ff"},
{"name":"Galician","code":"gl"},
{"name":"Gaelic(Scottish)","code":"gd"},
{"name":"Gaelic(Manx)","code":"gv"},
{"name":"Georgian","code":"ka"},
{"name":"German","code":"de"},
{"name":"Greek","code":"el"},
{"name":"Greenlandic","code":"kl"},
{"name":"Guarani","code":"gn"},
{"name":"Gujarati","code":"gu"},
{"name":"HaitianCreole","code":"ht"},
{"name":"Hausa","code":"ha"},
{"name":"Hebrew","code":"he"},
{"name":"Herero","code":"hz"},
{"name":"Hindi","code":"hi"},
{"name":"Hiri Motu","code":"ho"},
{"name":"Hungarian","code":"hu"},
{"name":"Icelandic","code":"is"},
{"name":"Ido","code":"io"},
{"name":"Igbo","code":"ig"},
{"name":"Indonesian","code":"in"},
{"name":"Interlingua","code":"ia"},
{"name":"Interlingue","code":"ie"},
{"name":"Inuktitut","code":"iu"},
{"name":"Inupiak","code":"ik"},
{"name":"Irish","code":"ga"},
{"name":"Italian","code":"it"},
{"name":"Japanese","code":"ja"},
{"name":"Javanese","code":"jv"},

{"name":"Kannada","code":"kn"},
{"name":"Kanuri","code":"kr"},
{"name":"Kashmiri","code":"ks"},
{"name":"Kazakh","code":"kk"},
{"name":"Khmer","code":"km"},
{"name":"Kikuyu","code":"ki"},
{"name":"Kinyarwanda(Rwanda)","code":"rw"},
{"name":"Kirundi","code":"rn"},
{"name":"Kyrgyz","code":"ky"},
{"name":"Komi","code":"kv"},
{"name":"Kongo","code":"kg"},
{"name":"Korean","code":"ko"},
{"name":"Kurdish","code":"ku"},
{"name":"Kwanyama","code":"kj"},
{"name":"Lao","code":"lo"},
{"name":"Latin","code":"la"},
{"name":"Latvian(Lettish)","code":"lv"},
{"name":"Limburgish(Limburger)","code":"li"},
{"name":"Lingala","code":"ln"},
{"name":"Lithuanian","code":"lt"},
{"name":"Luga-Katanga","code":"lu"},
{"name":"LugandaGanda","code":"lg"},
{"name":"Luxembourgish","code":"lb"},

{"name":"Macedonian","code":"mk"},
{"name":"Malagasy","code":"mg"},
{"name":"Malay","code":"ms"},
{"name":"Malayalam","code":"ml"},
{"name":"Maltese","code":"mt"},
{"name":"Maori","code":"mi"},
{"name":"Marathi","code":"mr"},
{"name":"Marshallese","code":"mh"},
{"name":"Moldavian","code":"mo"},
{"name":"Mongolian","code":"mn"},
{"name":"Nauru","code":"na"},
{"name":"Navajo","code":"nv"},
{"name":"Ndonga","code":"ng"},
{"name":"NorthernNdebele","code":"nd"},
{"name":"Nepali","code":"ne"},
{"name":"Norwegian","code":"no"},
{"name":"Norwegianbokmål","code":"nb"},
{"name":"Norwegiannynorsk","code":"nn"},
{"name":"Nuosu","code":"ii"},
{"name":"Occitan","code":"oc"},
{"name":"Ojibwe","code":"oj"},
{"name":"OldBulgarian","code":"cu"},
{"name":"Oriya","code":"or"},
{"name":"Oromo(AfaanOromo)","code":"om"},
{"name":"Ossetian","code":"os"},
{"name":"Pāli","code":"pi"},
{"name":"Pashto","code":"ps"},
{"name":"Persian(Farsi)","code":"fa"},
{"name":"Polish","code":"pl"},
{"name":"Portuguese","code":"pt"},
{"name":"Punjabi(Eastern)","code":"pa"},
{"name":"Quechua","code":"qu"},
{"name":"Romansh","code":"rm"},
{"name":"Romanian","code":"ro"},
{"name":"Russian","code":"ru"},
{"name":"Sami","code":"se"},
{"name":"Samoan","code":"sm"},
{"name":"Sango","code":"sg"},
{"name":"Sanskrit","code":"sa"},
{"name":"Serbian","code":"sr"},
{"name":"Serbo-Croatian","code":"sh"},
{"name":"Sesotho","code":"st"},
{"name":"Setswana","code":"tn"},
{"name":"Shona","code":"sn"},

{"name":"Sindhi","code":"sd"},
{"name":"Sinhalese","code":"si"},

{"name":"Slovak","code":"sk"},
{"name":"Slovenian","code":"sl"},
{"name":"Somali","code":"so"},
{"name":"SouthernNdebele","code":"nr"},
{"name":"Spanish","code":"es"},
{"name":"Sundanese","code":"su"},
{"name":"Swahili(Kiswahili)","code":"sw"},
{"name":"Swati","code":"ss"},
{"name":"Swedish","code":"sv"},
{"name":"Tagalog","code":"tl"},
{"name":"Tahitian","code":"ty"},
{"name":"Tajik","code":"tg"},
{"name":"Tamil","code":"ta"},
{"name":"Tatar","code":"tt"},
{"name":"Telugu","code":"te"},
{"name":"Thai","code":"th"},
{"name":"Tibetan","code":"bo"},
{"name":"Tigrinya","code":"ti"},
{"name":"Tonga","code":"to"},
{"name":"Tsonga","code":"ts"},
{"name":"Turkish","code":"tr"},
{"name":"Turkmen","code":"tk"},
{"name":"Twi","code":"tw"},
{"name":"Uyghur","code":"ug"},
{"name":"Ukrainian","code":"uk"},
{"name":"Urdu","code":"ur"},
{"name":"Uzbek","code":"uz"},
{"name":"Venda","code":"ve"},
{"name":"Vietnamese","code":"vi"},
{"name":"Volapük","code":"vo"},
{"name":"Wallon","code":"wa"},
{"name":"Welsh","code":"cy"},
{"name":"Wolof","code":"wo"},
{"name":"Western","code":"fy"},
{"name":"Xhosa","code":"xh"},
{"name":"Yiddish","code":"ji"},
{"name":"Yoruba","code":"yo"},
{"name":"Zhuang","code":"za"},
{"name":"Zulu","code":"zu"}]

export const JOBS = [
    {"name":"Auxiliary Nurse","code":1},
    {"name":"Acute Care Nurses","code":2},
    {"name":"Adapted Physical Education Specialists","code":3},
    {"name":"Accountant","code":4},
    {"name":"Account manager","code":5},
    {"name":"Actuaries","code":6},
    {"name":"Acupuncturists","code":7},
    {"name":"Advertising Sales Agents","code":8},
    {"name":"Cashier","code":9},
    {"name":"Cleaner","code":10},
    {"name":"Driver","code":11},
    {"name":"Developer","code":12},
    {"name":"IT","code":13},
    {"name":"Massotherapeute","code":14},
    {"name":"Painters","code":15},
    {"name":"Registered Nurse","code":16},
    {"name":"Snow removal Agent","code":17},
    {"name":"Security Agent","code":18},
    {"name":"Salespeople Retail","code":19},
    {"name":"Training","code":20},
    {"name":"Welder","code":21}
]

export const  USERCATEGORIES = [
    {"name":"Offering A Service","code":1},
    {"name":"Looking For A Service","code":2},
]